### ISSUE TITLE
Data-set generator

### ISSUE THREAD

**Issue by BobAubouin** [BobAubouin/hypotension_pred#1]
Implement the data-set generator:

- [x] patient selection
- [x] feature selection
- [x] format the code  
- [x] Reimplement data loading from API with async calls
- [x] Refactor dataset download
- [x] track_names and other possible change should be configurable with toml file.
- [x] refactor post process.

**Comment by BobAubouin** [comment]
- [ ] format the code

**Comment by AwePhD** [comment]
More to do

- [ ] Reimplement data loading from API with async calls
- [ ] Refactor dataset download
- [ ] track_names and other possible change should be configurable with toml file.

**Comment by AwePhD** [comment]
Discussion on post process (filtering track) solution.
[run-2024-02-22 09:18:07.701768.log](https://github.com/BobAubouin/hypotension_pred/files/14370943/run-2024-02-22.09.18.07.701768.log)

**Comment by AwePhD** [comment]
Done with #4
